# Generated by Django 4.0 on 2022-01-11 06:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=50, null=True)),
                ('technology_decs', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
