# Generated by Django 4.0 on 2022-01-11 07:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinomial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinomial_content', ckeditor.fields.RichTextField()),
                ('testinomial_image', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('testinomial_name', models.CharField(max_length=50, null=True)),
                ('testinomial_info', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
