# Generated by Django 4.0 on 2022-01-11 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_testinomial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('project_name', models.CharField(max_length=50, null=True)),
                ('project_desc', ckeditor.fields.RichTextField()),
                ('project_client', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
