# Generated by Django 4.0 on 2022-01-11 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blog_name', models.CharField(max_length=50, null=True)),
                ('blog_desc', ckeditor.fields.RichTextField()),
                ('project_footer', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
