# Generated by Django 4.0 on 2022-01-13 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_desc', ckeditor.fields.RichTextField()),
                ('answer_desc', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
