# Generated by Django 4.0 on 2022-01-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_answerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerable',
            name='question_no',
            field=models.IntegerField(null=True),
        ),
    ]
