# Generated by Django 4.0 on 2022-01-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Booking',
        ),
    ]
